#!/bin/sh
set -euo pipefail
IFS=$(printf '\n\t')

sxhkd &

bspc config border_width  2
bspc config window_gap   24

bspc config active_border_color   "#404040"
bspc config focused_border_color  "#7c60bf"
bspc config normal_border_color   "#404040"
bspc config presel_feedback_color "#7c60bf"

bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config split_ratio         0.52

bspc monitor -d term code http media misc
