#!/usr/bin/env sh
set -euo pipefail
IFS=$(printf '\n\t')

sxhkd &

bspc config border_width  2
bspc config window_gap   24

bspc config active_border_color   "#ffffff"
bspc config focused_border_color  "#d79fcf"
bspc config normal_border_color   "#ffffff"
bspc config presel_feedback_color "#d79fcf"

bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config split_ratio         0.52

bspc monitor -d term code http media misc
