flags:
    xmobar:
        all_extensions: true
packages:   []
extra-deps:
    - X11-xft-0.3.1
    - alsa-core-0.5.0.1
    - alsa-mixer-0.2.0.3
    - dbus-0.10.12
    - libxml-sax-0.7.5
    - xmobar-0.24.3
    - xmonad-0.13
    - xmonad-contrib-0.13
resolver:   lts-8.0
